services:
  - type: web
    name: unbc-picture-research
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn AppTest:app"
    envVars:
      - key: FLASK_ENV
        value: production
